# ISYS 574  Homework 1

This homework uses a dataset of individual diamonds, each with a set of physical and quality characteristics along with the price it sold for.

Your goal is to build a linear regression model that predicts a diamond price from the other diamond features. 
<br> You will evaluate your model using RMSE and iterate on it the way we covered in class.

Use this file to write your code; then submit this file on Canvas.
<br> You can add extra cells in each sections, as needed

**Write your name below**

# Name: Antonio Moore

In [1]:
#Use this cell to import the required libraries
import numpy as np
import pandas as pd

## 1. Load & Understand the Data (2 pts)
* Load the Diamond.csv file into a DataFrame. 
* Get an overview: shape, column names, data types

In [2]:
df = pd.read_csv('Diamonds.csv')

In [3]:
df

      carat  depth  table     x     y     z        cut color clarity  price
0      0.33   61.7   55.0  4.43  4.46  2.74      Ideal     H     SI1    564
1      1.20   62.1   57.0  6.78  6.71  4.19      Ideal     I     VS2   5914
2      0.62   61.0   57.0  5.51  5.54  3.37      Ideal     D     VS1   2562
3      0.34   63.1   56.0  4.41  4.46  2.80       Good     H     VS2    537
4      1.20   62.5   55.0  6.77  6.84  4.25      Ideal     E     SI2   5964
...     ...    ...    ...   ...   ...   ...        ...   ...     ...    ...
2995   1.17   60.6   60.0  6.81  6.79  4.12    Premium     G     VS1   7666
2996   0.30   63.2   57.0  4.21  4.24  2.67       Good     D     SI2    447
2997   0.90   62.3   61.0  6.12  6.17  3.83  Very Good     E     SI1   3868
2998   1.07   59.4   59.0  6.64  6.70  3.96  Very Good     F      IF  11019
2999   0.30   63.2   59.0  4.31  4.27  2.71  Very Good     H     VS1    639

[3000 rows x 10 columns]

In [4]:
df.shape

(3000, 10)

In [5]:
df.columns

Index(['carat', 'depth', 'table', 'x', 'y', 'z', 'cut', 'color', 'clarity',
       'price'],
      dtype='str')

In [6]:
df.dtypes

carat      float64
depth      float64
table      float64
x          float64
y          float64
z          float64
cut            str
color          str
clarity        str
price        int64
dtype: object

In [7]:
df.info

<bound method DataFrame.info of       carat  depth  table     x     y     z        cut color clarity  price
0      0.33   61.7   55.0  4.43  4.46  2.74      Ideal     H     SI1    564
1      1.20   62.1   57.0  6.78  6.71  4.19      Ideal     I     VS2   5914
2      0.62   61.0   57.0  5.51  5.54  3.37      Ideal     D     VS1   2562
3      0.34   63.1   56.0  4.41  4.46  2.80       Good     H     VS2    537
4      1.20   62.5   55.0  6.77  6.84  4.25      Ideal     E     SI2   5964
...     ...    ...    ...   ...   ...   ...        ...   ...     ...    ...
2995   1.17   60.6   60.0  6.81  6.79  4.12    Premium     G     VS1   7666
2996   0.30   63.2   57.0  4.21  4.24  2.67       Good     D     SI2    447
2997   0.90   62.3   61.0  6.12  6.17  3.83  Very Good     E     SI1   3868
2998   1.07   59.4   59.0  6.64  6.70  3.96  Very Good     F      IF  11019
2999   0.30   63.2   59.0  4.31  4.27  2.71  Very Good     H     VS1    639

[3000 rows x 10 columns]>

In [8]:
df.describe(include='all')

,carat,depth,table,x,y,z,cut,color,clarity,price
count,3000.000000,2850.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000,3000,3000,3000.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,5,7,8,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,Ideal,G,SI1,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,1200,635,753,NaN
mean,0.804837,61.793333,57.403433,5.754460,5.755510,3.553240,NaN,NaN,NaN,3966.751000
std,0.464427,1.462607,2.219311,1.102141,1.094363,0.689467,NaN,NaN,NaN,3943.221253
min,0.210000,55.800000,52.000000,3.850000,3.840000,0.000000,NaN,NaN,NaN,339.000000
25%,0.400000,61.000000,56.000000,4.740000,4.750000,2.930000,NaN,NaN,NaN,947.750000
50%,0.710000,61.900000,57.000000,5.720000,5.740000,3.550000,NaN,NaN,NaN,2552.000000
75%,1.050000,62.500000,59.000000,6.560000,6.550000,4.040000,NaN,NaN,NaN,5419.500000
max,3.010000,70.600000,68.000000,9.100000,8.970000,5.670000,NaN,NaN,NaN,18730.000000

## 2. Data Preparation (2 pts)
* Check the dataset for consistency issues: column naming, spacing, casing

### Column Cleaning

In [13]:
df.columns

Index(['carat', 'depth', 'table', 'x', 'y', 'z', 'cut', 'color', 'clarity',
       'price'],
      dtype='str')

In [9]:
# Remove anything above or after the string
df.columns = df.columns.str.strip()

In [10]:
# Convert every letter in the string to a lowercase
df.columns = df.columns.str.lower()

In [11]:
#Make spaces obvious
df.columns = df.columns.str.replace(' ', '_')

In [12]:
df.columns

Index(['carat', 'depth', 'table', 'x', 'y', 'z', 'cut', 'color', 'clarity',
       'price'],
      dtype='str')

### Data Cleaning

In [19]:
df['cut'].unique()

<ArrowStringArray>
['Ideal', 'Good', 'Premium', 'Very Good', 'Fair']
Length: 5, dtype: str

In [20]:
df['color'].unique()

<ArrowStringArray>
['H', 'I', 'D', 'E', 'G', 'F', 'J']
Length: 7, dtype: str

In [21]:
df['clarity'].unique()

<ArrowStringArray>
['SI1', 'VS2', 'VS1', 'SI2', 'VVS2', 'IF', 'VVS1', 'I1']
Length: 8, dtype: str

## 3. Exploratory Data Analysis (3 pts)
* Explore each column. Look at the number of unique values in the categorical columns
* Plot a histogram of price, and decide whether a log transform is needed

## 4. Create Train / Validation / Test Sets (2 pts)
* Shuffle and split the data into a 60% train / 20% validation / 20% test set
* Make sure to separate the target data for each set

## 5. Apply Linear Regression: Numerical Features Only (4 pts)
* Build a prepare_X() function using only the numerical columns. Decide on how to manage possible missing values
* Train your model
* Compute the training RMSE
* Try predicting on the validation set

## 6. Feature Engineering 1 (3 pts)
* Consider whether any existing columns could be transformed into something more useful: Hint: volume = length x width x depth
  
* Update prepare_X() and re-evaluate

## 7. Feature Engineering 2: Categorical Variables (4 pts)
* Assess your categorical columns
* One-hot encode your categorical columns. Don't forget to have a reference value to exclude
* Update prepare_X() and re-evaluate

## 8. Evaluate & Iterate (3 pts)
* Compare your validation RMSE across every version of your model so far (numerical-only, after missing values, after feature engineering, after categorical encoding).

## 9. Final Model on the Test Set (2 pts)
* Once you're satisfied with your model based on validation performance, run it once on the test set and report the test RMSE.
* Pick a few random diamonds from the test set and compare predicted vs. actual price.